### PR TITLE
Adobe ExtendScript errors

### LINKED ISSUE #31: Adobe ExtendScript errors with self and certain regular expressions
We were addressing an unexpected issue about running in Adobe ExtendScript https://github.com/SheetJS/js-xlsx/issues/603. 
 It's the scripting runtime for Adobe products, and it claims to be "extended" ECMAScript. 

After some digging, we found two issues:

1) `self` is not available in extendscript and the object assignment assumes `self` is defined:

```js
  var object = typeof exports != 'undefined' ? exports : self; // #8: web workers
  // when exports and self are both undefined, this line fails thanks to the unguarded assignment 
```

The indirect eval trick `(1,eval)('this')` appeared to work:
```js
  var object = typeof exports != 'undefined' ? exports : typeof self != 'undefined' ? self : (1,eval)('this')
```

2) Regular expression literals starting with `=` are problematic:

screen shot 2017-03-23 at 19 32 44

I believe the fix here is to turn `/=+$/` into a RegExp call: `new RegExp("=+$")`

### PR DESCRIPTION
**Pull request by SheetJSDev**
Fixes #31:
- ES parses `/=+$/` as a division-assignment; replace with new RegExp
- fallback to global eval if `self` and `exports` are not available

```
$ make bytes
gzip --best --stdout base64.min.js | wc -c | tr -d ' '
568
$ make test
  ․․․․․․

  6 passing (10ms)
=============================== Coverage summary ===============================
Statements   : 100% ( 22/22 )
Branches     : 85% ( 17/20 )
Functions    : 100% ( 4/4 )
Lines        : 100% ( 22/22 )
================================================================================
```

### CODE REVIEW

**Comment by davidchambers** [comment]
Thank you for submitting this pull request, @SheetJSDev!

File: base64.js [hunk 1]
```diff
@@ -37,7 +37,7 @@
   // [https://gist.github.com/1020396] by [https://github.com/atk]
   object.atob || (
   object.atob = function (input) {
-    var str = String(input).replace(/=+$/, '');
+    var str = String(input).replace(new RegExp("=+$"), ''); // #31: ExtendScript bad parse of /=
```
Comment (davidchambers) [inline base64.js]: Did you see @michaelficarra's suggestion in #31? It strikes me as a nice approach. Another option is `/[=]+$/` (I just tested it in ExtendScript Toolkit).

I'm happy with any of these three fixes. @michaelficarra, do you have a preference?

Comment (SheetJSDev) [inline base64.js]: @davidchambers `/[=]+$/` is probably ubiquitous since any reasonable regexp library will support character sets.  I don't know what engines support non-capture groups (which was @michaelficarra 's suggestion)

In the interest of parsimony `/[=]+$/` only adds 2 characters to the output while `/(?:)=+$/` adds 4 and `new RegExp` adds many more, so that is probably the best option

Comment (SheetJSDev) [inline base64.js]: If we come to a consensus I can change the commit, but let's wait for @michaelficarra to chime in first.

File: base64.js [hunk 2]
```diff
@@ -1,6 +1,6 @@
 ;(function () {
 
-  var object = typeof exports != 'undefined' ? exports : self; // #8: web workers
+  var object = typeof exports != 'undefined' ? exports : typeof self != 'undefined' ? self : (1,eval)('this'); // #8: web workers, #31: ExtendScript
```
Comment (davidchambers) [inline base64.js]: Does this work for you? For me,

```javascript
(function() { return (1, eval)('this'); }())
```

evaluates to a reference to the anonymous function. On the other hand,

```javascript
(function(global) { return global; }(this))
```

evaluates to the global object.

Now that we have three cases we could reformat the ternary expressions to improve readability. I suggest something along these lines:

```javascript
var object =
  typeof exports != 'undefined' ? exports :
  typeof self != 'undefined'    ? self :
  /* otherwise */                 ...;
```

Comment (SheetJSDev) [inline base64.js]: @davidchambers `1,eval` trick works in the illustrator context but not in the photoshop context.  I couldn't get your function working either.  So I went back to the docs https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/scripting/pdfs/javascript_tools_guide.pdf and it says `$.global` should be available everywhere.

Can you check if `$.global` works for you?  

Also, what should happen if none of the variables are available?  The original code assumed `self` was available

Comment (davidchambers) [inline base64.js]: > Can you check if `$.global` works for you?

It does. Let's use it!

> Also, what should happen if none of the variables are available?

I'm happy to leave the behaviour unspecified.

**Comment by SheetJSDev** [comment]
Amended commit with the discussed changes.  Thanks @davidchambers for looking into this on a Saturday :)

**Comment by davidchambers** [comment]
Released as [1.0.1][1]. Thank you for the thoughtful pull request, @SheetJSDev. :)


[1]: https://github.com/davidchambers/Base64.js/releases/tag/1.0.1
